included: # paths to include during linting. `--path` is ignored if present.
  - champion-tracker
  - SamplePlayer
excluded: # paths to ignore during linting. Takes precedence over `included`.
disabled_rules:
  - type_body_length
  - file_length
  - nesting
identifier_name:
  min_length: 2
  max_length: 40
line_length: 160
